Repository integr8ly/cloud-resource-operator, pull requests merged in 2019-12, with the labels that each got.

#64 generate cluster service versions
  Makefile
  README.md
  deploy/cluster_role.yaml
  deploy/olm-catalog/cloud-resources/0.3.0/cloud-resources.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.3.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.3.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.3.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.3.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XL

#69 refactor openshift deletion
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
Labels: approved, lgtm, size/L

#66 fix credentials secret name clash
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_postgres_test.go
Labels: approved, lgtm, size/L

#72 add more details to the vpc peering documentation
  README.md
Labels: approved, lgtm, size/M

#71 bump version to 0.4.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.4.0/cloud-resources.v0.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.4.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.4.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.4.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.4.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XL

#76 add new run service account target
  Makefile
  deploy/role_binding.yaml
Labels: approved, lgtm, size/S

#77 add skip create logic to aws redis and postgres
  README.md
  deploy/crds/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/crds/integreatly_v1alpha1_postgres_crd.yaml
  deploy/crds/integreatly_v1alpha1_redis_crd.yaml
  deploy/crds/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/L

#78 Add delete status
  go.mod
  go.sum
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/openshift/provider_blobstorage.go
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
  pkg/providers/openshift/provider_smtpcredentialset.go
  pkg/providers/types.go
  pkg/resources/phase.go
  pkg/resources/provider.go
  pkg/resources/util.go
Labels: approved, lgtm, size/L

#80 Update seed targets
  Makefile
  deploy/crds/integreatly_v1alpha1_blobstorage_cr.yaml
  deploy/crds/integreatly_v1alpha1_postgres_cr.yaml
  deploy/crds/integreatly_v1alpha1_redis_cr.yaml
  deploy/crds/integreatly_v1alpha1_smtpcredentialset_cr.yaml
Labels: approved, lgtm, size/M
