Repository integr8ly/cloud-resource-operator, pull requests merged in 2019-11, with the labels that each got.

#36 refactor e2e tests
  cmd/manager/main.go
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
  deploy/role.yaml
  test/e2e/cro_test.go
  test/e2e/openshift_postgres_test.go
  test/e2e/openshift_redis_test.go
Labels: Verified

#45 add vpc peering connection steps
  README.md
  deploy/crds/integreatly_v1alpha1_blobstorage_cr.yaml
  deploy/crds/integreatly_v1alpha1_postgres_cr.yaml
  deploy/crds/integreatly_v1alpha1_redis_cr.yaml
  deploy/crds/integreatly_v1alpha1_smtpcredentialset_cr.yaml
  deploy/examples/cloud_resources_aws_strategies.yaml
  doc/blobstorage.md
Labels: approved, lgtm, size/M

#41 Coverall file reduction
  Makefile
  go.mod
  pkg/apis/integreatly/v1alpha1/blobstorage_types.go
  pkg/apis/integreatly/v1alpha1/postgres_types.go
  pkg/apis/integreatly/v1alpha1/redis_types.go
  pkg/apis/integreatly/v1alpha1/smtpcredentialset_types.go
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/apis/integreatly/v1alpha1/types/types_test.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller_test.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_blobstorage_test.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/aws/provider_smtpcredentialset_test.go
  pkg/providers/config.go
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_postgres_test.go
  pkg/providers/openshift/provider_redis.go
  pkg/providers/openshift/provider_redis_test.go
  pkg/providers/types.go
  pkg/providers/types_moq.go
  pkg/resources/phase.go
  pkg/resources/provider.go
  pkg/resources/util.go
  pkg/resources/util_test.go
  test/e2e/openshift_postgres_test.go
  test/e2e/openshift_redis_test.go
Labels: approved, lgtm, size/XL

#47 Openshift Basic Providers
  Makefile
  go.mod
  go.sum
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/aws/provider_smtpcredentialset_test.go
  pkg/providers/openshift/provider_blobstorage.go
  pkg/providers/openshift/provider_blobstorage_test.go
  pkg/providers/openshift/provider_smtpcredentialset.go
  pkg/providers/openshift/provider_smtpcredentialset_test.go
  pkg/resources/strings.go
  pkg/resources/strings_test.go
  test/e2e/cro_test.go
  test/e2e/openshift_blobstorage_test.go
  test/e2e/openshift_smtp_test.go
Labels: approved, lgtm, size/XXL, ¯\_(ツ)_/¯

#48 add prow e2e setup
  Makefile
Labels: approved, lgtm, size/XS

#49 travis tag stage fix
  .travis.yml
Labels: approved, lgtm, size/XS

#50 update prow setup command
  Makefile
Labels: approved, lgtm, size/XS

#51 Update e2e tests to latest cro types
  go.mod
  go.sum
  test/e2e/openshift_blobstorage_test.go
  test/e2e/openshift_smtp_test.go
Labels: approved, lgtm, size/S

#52 update prow setup and test target
  Makefile
Labels: approved, lgtm, size/S

#54 add go module on to prow e2e
  Makefile
Labels: approved, lgtm, size/XS

#55 update vpc peering docs for security groups
  README.md
Labels: approved, lgtm, size/XS

#56 set defaults to openshift
  pkg/providers/config.go
Labels: approved, lgtm, size/XS

#57 Updating operator-sdk to v0.12.0
  Makefile
  cmd/manager/main.go
  deploy/crds/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/crds/integreatly_v1alpha1_postgres_crd.yaml
  deploy/crds/integreatly_v1alpha1_redis_crd.yaml
  deploy/crds/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/blobstorage_types.go
  pkg/apis/integreatly/v1alpha1/redis_types.go
  pkg/apis/integreatly/v1alpha1/register.go
  pkg/apis/integreatly/v1alpha1/smtpcredentialset_types.go
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
  pkg/resources/provider.go
  pkg/resources/util.go
  tools.go
Labels: approved, lgtm, size/XL

#58 feat: Add monitoring label to operator service monitor
  Makefile
  cmd/manager/main.go
  go.mod
Labels: approved, lgtm, size/M

#59 provide production defaults for openshift
  pkg/providers/openshift/config.go
Labels: approved, lgtm, size/S

#60 bump version to 0.2.0
  Makefile
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/S

#63 bump version to 0.3.0
  Makefile
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/cloud-resource-operator.package.yaml
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/M
