Repository integr8ly/cloud-resource-operator, pull requests merged in 2020-01, with the labels that each got.

#74 Intly 3968 all tagging
  README.md
  deploy/crds/integreatly_v1alpha1_blobstorage_cr.yaml
  deploy/crds/integreatly_v1alpha1_postgres_cr.yaml
  deploy/crds/integreatly_v1alpha1_redis_cr.yaml
  deploy/crds/integreatly_v1alpha1_smtpcredentialset_cr.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_blobstorage_test.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/resources/config.go
  pkg/resources/config_test.go
  pkg/resources/util.go
Labels: approved, lgtm, size/XL

#81 Add productName label to CRs
  Makefile
  deploy/olm-catalog/cloud-resources/0.5.0/cloud-resources.v0.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.5.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.5.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.5.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.5.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/resources/util.go
  pkg/resources/util_test.go
  version/version.go
Labels: approved, lgtm, size/XXL

#84 make gen/csv makefile target portable
  Makefile
Labels: approved, lgtm, size/XS

#85 Fixed redis log message
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/XS

#83 Allow arbitrary redis and elasticache snapshots
  Makefile
  README.md
  deploy/crds/integreatly_v1alpha1_postgressnapshot_cr.yaml
  deploy/crds/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/crds/integreatly_v1alpha1_redissnapshot_cr.yaml
  deploy/crds/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/cloud-resources.v0.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/integreatly/v1alpha1/postgressnapshot_types.go
  pkg/apis/integreatly/v1alpha1/redissnapshot_types.go
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_postgressnapshot.go
  pkg/controller/add_redissnapshot.go
  pkg/controller/postgressnapshot/postgressnapshot_controller.go
  pkg/controller/postgressnapshot/postgressnapshot_controller_test.go
  pkg/controller/redissnapshot/redissnapshot_controller.go
  pkg/controller/redissnapshot/redissnapshot_controller_test.go
  pkg/providers/aws/config.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/resources/config.go
  pkg/resources/phase.go
  vendor/modules.txt
  version/version.go
Labels: approved, lgtm, size/XXL

#86 Fix CSV Formatting & Add Product Name to Util Function
  deploy/olm-catalog/cloud-resources/0.6.0/cloud-resources.v0.6.0.clusterserviceversion.yaml
  pkg/resources/config.go
  pkg/resources/util.go
  pkg/resources/util_test.go
Labels: approved, lgtm, size/L

#87 Added custom metrics for AWS RDS and ElastiCache scheduled maintenance
  go.mod
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  pkg/resources/custom_metrics.go
Labels: approved, lgtm, size/L

#89 fixed linting errors in ClusterId
  README.md
  pkg/providers/aws/config.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  pkg/resources/cluster.go
Labels: approved, lgtm, size/M

#92 Volume permissions fix
  Makefile
  deploy/olm-catalog/cloud-resources/0.6.1/cloud-resources.v0.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.6.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/openshift/config.go
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/XL

#91 add available metrics
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
Labels: approved, lgtm, size/L

#95 Added some comments
  pkg/providers/config.go
  pkg/providers/types.go
  pkg/resources/finalizers.go
  pkg/resources/phase.go
  pkg/resources/strings.go
Labels: approved, lgtm, size/S

#93 Intly 4941 remove stuttering
  pkg/providers/aws/credentials.go
  pkg/providers/aws/credentials_moq.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/providers/aws/provider_smtpcredentialset_test.go
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_postgres_test.go
  pkg/providers/openshift/provider_redis.go
  pkg/providers/openshift/provider_redis_test.go
Labels: approved, lgtm, size/L

#96 Default CRO to MultiAZ deployments
  Makefile
  README.md
  deploy/olm-catalog/cloud-resources/0.7.0/cloud-resources.v0.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  version/version.go
Labels: approved, lgtm, size/XL

#98 Update redis openshift deployment memory request
  Makefile
  README.md
  deploy/olm-catalog/cloud-resources/0.7.1/cloud-resources.v0.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/openshift/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/XL

#94 fixed comment syntax
  pkg/apis/integreatly/v1alpha1/smtpcredentialset_types.go
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
  pkg/providers/aws/config.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/config.go
  pkg/providers/openshift/config.go
  pkg/providers/types.go
  pkg/resources/config.go
  pkg/resources/custom_metrics.go
  pkg/resources/strings.go
Labels: approved, lgtm, size/M

#97 Create new Alert (PrometheusRule) AWS resources being available
  Makefile
  cmd/manager/main.go
  deploy/role.yaml
  go.mod
  go.sum
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/resources/custom_metrics.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/crd_kinds.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/go-openapi/swag/.gitignore
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/doc.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/name_lexem.go
  vendor/github.com/go-openapi/swag/net.go
  vendor/github.com/go-openapi/swag/post_go18.go
  vendor/github.com/go-openapi/swag/post_go19.go
  vendor/github.com/go-openapi/swag/pre_go18.go
  vendor/github.com/go-openapi/swag/pre_go19.go
  vendor/github.com/go-openapi/swag/split.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/go-openapi/swag/yaml.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#100 bump version to 0.7.2
  Makefile
  deploy/olm-catalog/cloud-resource-operator/cloud-resource-operator.package.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/cloud-resources.v0.7.2.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.7.2/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#102 fix namespace prefix error
  Makefile
  deploy/olm-catalog/cloud-resource-operator/cloud-resource-operator.package.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/cloud-resources.v0.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/aws/provider_postgres.go
  pkg/providers/openshift/config.go
  pkg/providers/openshift/provider_postgres.go
  pkg/providers/openshift/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/XL
