Repository integr8ly/cloud-resource-operator, pull requests merged in 2020-02, with the labels that each got.

#103 Targetting exported_namespace in metric alerts
  cmd/manager/main.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/S

#104 bump cro v0.8.1
  Makefile
  deploy/olm-catalog/cloud-resources/0.8.1/cloud-resources.v0.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#105 Adding cluster role permissions to CRO to manage PrometheusRules
  deploy/cluster_role.yaml
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/M

#106 Bump CRO to v0.8.2
  Makefile
  deploy/olm-catalog/cloud-resources/0.8.2/cloud-resources.v0.8.2.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.8.2/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XL

#101 Deploy CRO resources in the cluster VPC
  deploy/crds/integreatly_v1alpha1_postgres_cr.yaml
  deploy/crds/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/crds/integreatly_v1alpha1_redissnapshot_crd.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_config_v1.go
  pkg/apis/addtoscheme_oapi_config_v1.go
  pkg/apis/config/group.go
  pkg/apis/config/v1/doc.go
  pkg/apis/config/v1/infrastructure_types.go
  pkg/apis/config/v1/register.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/apis/config/v1/zz_generated.openapi.go
  pkg/apis/integreatly/v1alpha1/types/types.go
  pkg/apis/integreatly/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/integreatly/v1alpha1/zz_generated.openapi.go
  pkg/controller/postgressnapshot/postgressnapshot_controller.go
  pkg/controller/postgressnapshot/postgressnapshot_controller_test.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/redissnapshot/redissnapshot_controller.go
  pkg/controller/redissnapshot/redissnapshot_controller_test.go
  pkg/providers/aws/cluster_vpc.go
  pkg/providers/aws/config.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/credentials_moq.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/aws/provider_smtpcredentialset_test.go
  pkg/providers/config.go
  pkg/providers/openshift/provider_postgres.go
  pkg/resources/cluster.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/errors.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/service.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#108 bump version 0.9.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.9.0/cloud-resources.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.9.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#111 fix region reconciliation in aws service providers
  go.mod
  pkg/controller/postgressnapshot/postgressnapshot_controller.go
  pkg/controller/redissnapshot/redissnapshot_controller.go
  pkg/providers/aws/config.go
  pkg/providers/aws/config_test.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_smtpcredentialset.go
  pkg/providers/aws/provider_smtpcredentialset_test.go
  pkg/resources/cluster.go
Labels: approved, lgtm, size/L

#112 Bump cro to version 0.10.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.10.0/cloud-resources.v0.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.10.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#109 Connection Metric
  go.mod
  go.sum
  pkg/providers/aws/connection_tester.go
  pkg/providers/aws/connection_tester_moq.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/resources/custom_metrics.go
  vendor/github.com/lib/pq/conn_go18.go
  vendor/github.com/lib/pq/copy.go
  vendor/github.com/lib/pq/encode.go
  vendor/github.com/lib/pq/scram/scram.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#113 Remove Alerts and Bump 0.11.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.11.0/cloud-resources.v0.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.11.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  pkg/resources/custom_metrics.go
  version/version.go
Labels: approved, lgtm, size/XL

#114 add conditions to not except changes in cloud-resource-config in an existing install
  pkg/controller/blobstorage/blobstorage_controller.go
  pkg/controller/postgres/postgres_controller.go
  pkg/controller/redis/redis_controller.go
  pkg/controller/smtpcredentialset/smtpcredentialset_controller.go
Labels: approved, lgtm, size/M

#107 ensure privacy settings are set correctly for each resource that the cloud resource operator provides via aws
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_blobstorage_test.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/M

#118 Postgres/Redis connection metric function refactor
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/M

#116 bump version 0.13.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.12.0/cloud-resources.v0.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.12.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#115 fix handle modify aws instance
  pkg/providers/aws/config.go
  pkg/providers/aws/credentials.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_postgres_test.go
  pkg/providers/aws/provider_redis.go
  pkg/providers/aws/provider_redis_test.go
  pkg/resources/configmaps.go
Labels: approved, lgtm, size/L

#119 bump version 0.13.0
  Makefile
  deploy/olm-catalog/cloud-resources/0.13.0/cloud-resources.v0.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.0/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/aws/provider_redis.go
  pkg/resources/configmaps.go
  version/version.go
Labels: approved, lgtm, size/XL

#120 set backup retention settings for elasticache instances to 31 days
  Makefile
  deploy/olm-catalog/cloud-resources/0.13.1/cloud-resources.v0.13.1.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.1/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/providers/aws/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/XL
