Repository integr8ly/cloud-resource-operator, pull requests merged in 2020-03, with the labels that each got.

#121 🐛 If resource marked as created, don't try create
  Makefile
  deploy/olm-catalog/cloud-resources/0.13.2/cloud-resources.v0.13.2.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.2/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  pkg/annotations/annotations.go
  pkg/providers/aws/config.go
  pkg/providers/aws/provider_blobstorage.go
  pkg/providers/aws/provider_blobstorage_test.go
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
  version/version.go
Labels: approved, lgtm, size/XL

#122 intly-6233 Final snapshots for RDS and Elasticache do not contain tags for teardown
  pkg/providers/aws/provider_postgres.go
  pkg/providers/aws/provider_redis.go
Labels: approved, lgtm, size/S

#123 bump version to 0.13.3
  Makefile
  deploy/olm-catalog/cloud-resources/0.13.3/cloud-resources.v0.13.3.clusterserviceversion.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_blobstorage_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_postgres_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_postgressnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_redis_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_redissnapshot_crd.yaml
  deploy/olm-catalog/cloud-resources/0.13.3/integreatly_v1alpha1_smtpcredentialset_crd.yaml
  deploy/olm-catalog/cloud-resources/cloud-resources.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm
